sonar.organization=tayyabkhan10
sonar.projectKey=tayyabkhan10_cohort-9-mern-16394-tayyab

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src/__tests__

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8